# Generated by Django 5.2.7 on 2025-10-17 11:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nama Bahan')),
                ('type', models.CharField(choices=[('BB', 'Bahan Baku'), ('BSJ', 'Bahan Setengah Jadi'), ('BHP', 'Bahan Habis Pakai')], max_length=3, verbose_name='Tipe Bahan')),
                ('unit', models.CharField(help_text='Contoh: gram, ml, pcs', max_length=20, verbose_name='Satuan Unit')),
                ('stock', models.FloatField(default=0, verbose_name='Stok Saat Ini')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Modal per Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Waktu Transaksi')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Harga')),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Uang Tunai')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kembalian')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nama Produk')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Harga Jual')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.category', verbose_name='Kategori')),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_produced', models.FloatField(verbose_name='Jumlah Dihasilkan')),
                ('production_date', models.DateField(default=django.utils.timezone.now)),
                ('ingredient_produced', models.ForeignKey(limit_choices_to={'type': 'BSJ'}, on_delete=django.db.models.deletion.CASCADE, to='kasir.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Jumlah yang Dibutuhkan')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.ingredient')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='kasir.product')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kasir.product')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='kasir.transaction')),
            ],
        ),
    ]
