# Generated by Django 5.2.7 on 2025-10-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kasir', '0002_transaction_transactiondetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Uang Tunai'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kembalian'),
        ),
    ]
